# Linear Algebra Uni Notes / Playground
This notebook is dedicated to playing around with LinAlg concepts in Python in order to gain a more intuitive understanding. I'll try to keep everything structured and well-explained, but no guarantees...
If I'm having troubles understanding any concept, it'll appear in this notebook.        
## 1. Playing around with the linalg np package

In [3]:
from numpy import linalg as la
import numpy as np

from IPython.display import display

In [21]:
A = np.random.rand(3,3)
B = np.array([[1, 0, 0],
              [0, 1, 0],
              [0, 0, 1]])
C = np.array([[1, 2, 4],
              [0, 0, 0],
              [0, 0, 0]])
display(A, B)

array([[0.99558256, 0.7204289 , 0.11550089],
       [0.02886177, 0.38987577, 0.72597734],
       [0.9277433 , 0.6418313 , 0.79999234]])

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [22]:
#Basic matrix computations:
la.det(A)

0.27557514981046366

In [23]:
la.det(B)

1.0

In [24]:
la.norm(B, 2)

1.0

In [25]:
la.eig(B)

(array([1., 1., 1.]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

In [26]:
la.matrix_rank(A)

3

In [28]:
la.matrix_rank(C)

1

In [31]:
la.inv(B)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
la.inv(B) @ B

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Applying (my current understanding of) eigendecomposition
From the [Wikipedia article on eigendecomposition](https://en.m.wikipedia.org/wiki/Eigendecomposition_of_a_matrix):<br>
"In linear algebra, eigendecomposition or sometimes spectral decomposition is the factorization of a matrix into a canonical form, whereby the matrix is represented in terms of its eigenvalues and eigenvectors. Only diagonalizable matrices can be factorized in this way."<br>
Specifically, a matrix can be represented as  
$$A=QΛQ^{-1}$$
where $Q$'s columns are the eigenvectors of $A$ and $Λ$ is a diagonal matrix with $A$'s eigenvalues as diagonal elements.  
This concept is easy to grasp once matrices are understood in a geometric way rather than purely mathematically:<br>![Derivation of eigendecomposition](derivation.png)<br>
As eigenvectors are only scaled, not rotated, by a matrix transformation, we can equate the product of a matrix and its eigenvector to the factor by which this eigenvector is scaled times this eigenvector. This is generalized include all the eigenvectors (columns of Q) and all the eigenvalues (diagonal elements of Λ). After rearranging, the decomposition relationship is done.

In [33]:
A = np.random.rand(2, 2)

λ, Q = la.eig(A)
Λ = np.array([[λ[0], 0], 
              [0, λ[1]]])
A_star = Q @ Λ @ la.inv(Q)
A_star, A #Equal, so it worked, yay!

(array([[0.81557044, 0.01433876],
        [0.06923305, 0.72515819]]),
 array([[0.81557044, 0.01433876],
        [0.06923305, 0.72515819]]))

## Orthonormal Matrices
An orthogonal matrix is a matrix whose rows and columns are orthogonal. On [wikipedia](https://en.wikipedia.org/wiki/Invertible_matrix#Eigendecomposition), it says<br>"Since $Q$ is formed from the eigenvectors of $A$, it is guaranteed to be an orthogonal matrix, therefore $Q^{-1}=Q^{T}$."  
An intuition for why this holds was needed, so [this](https://math.stackexchange.com/questions/1766669/why-if-a-matrix-q-is-orthogonal-then-qt-q-i) stackexchange thread came to my rescue.

In [ ]:
#TODO: add this section